[package]
name = "ddns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.22", features = ["cargo", "derive"] }
log = "0.4.17"
stderrlog = "0.5.4"
ureq = "2.5.0"
